### ISSUE TITLE
Id constraints

### ISSUE THREAD

**Issue by wwwgo-pl** [RalfEggert/zend-expressive-tutorial#1]
Hello. I think id constraint should be [1-9][0-9]*. Template config points to unexisting template/app.

**Comment by RalfEggert** [comment]
Fixed both.

https://github.com/RalfEggert/zend-expressive-tutorial/commit/87e1718b59c80117a8ad065292622ed5fb8e8d59

https://github.com/RalfEggert/zend-expressive-tutorial/commit/53a3a4e643d669f299b18fda73f4ac9c6cd24f5d
