### ISSUE TITLE
How should I go about reviewing?

### ISSUE THREAD

**Issue by weierophinney** [RalfEggert/zend-expressive-tutorial#14]
Hi, Ralf!

I'm ready to start reviewing this now, but would like some pointers as to how to proceed.

I can see that the repository has six branches, parts 1–6. The docs have a chapter for each, and, from what I can see, these are the same across all 6 branches. Am I to assume, then, that it is only the code that changes between the branches?

If so, my plan of action is:
- Review each chapter individually, in order.
- Review the code for each chapter.

I will then provide pull requests and/or issues to report feedback. Does that make sense?

Thanks!

**Comment by RalfEggert** [comment]
@weierophinney 

Yes, you are right. The docs are the same in each branch, only the code changes. That makes it easier to spot the differences between the branches. 

Your plan makes a lot of sense. I will merge all code PRs to the relevant branch and the docs changes to all branches.

**Comment by RalfEggert** [comment]
Closed
