### ISSUE TITLE
Incorrect factory name

### ISSUE THREAD

**Issue by SBC-Dana** [RalfEggert/zend-expressive-tutorial#19]
Hi Ralph, 

I'm following through the tutorial and noticed that in documentation for "Part 2: Album list middleware" under "Setup factory for album list middleware" it states  "Please create a  AlbumListActionFactory.php file".  This is incorrect as the rest of the code references this factory as AlbumListFactory. I believe the easiest fix would be to change the file name to "AlbumListFactory.php".  Or, the code could be changed to reference "AlbumListActionFactory" instead of "AlbumListFactory".

Thanks for the great tutorial !!

**Comment by RalfEggert** [comment]
This was fixed with one of the last commits
