### ISSUE TITLE
composer issues

### ISSUE THREAD

**Issue by webdesign7** [RalfEggert/zend-expressive-tutorial#21]
Hello, 

Thanks for the tutorial. Much appreciated ! :) 

I got an error when downloading the zend-db through composer : 
any ideas ( see below ) ?  _I haven't changed anything in composer.json ( literally downloaded the skeleton through composer then tried to import zend-db through composer._

---

Sergius-MacBook-Pro:zend-expressive-tutorial sergiu$ composer require zendframework/zend-db
Using version ^2.6 for zendframework/zend-db
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package ocramius/proxy-manager == 2.0.0.0 could not be found.
  Problem 2
    - The requested package filp/whoops == 2.0.0.0 could not be found.
  Problem 3
    - zendframework/zend-code 2.4.9 requires zendframework/zend-eventmanager 2.4.9 -> satisfiable by zendframework/zend-eventmanager[2.4.9].
    - zendframework/zend-code 2.4.8 requires zendframework/zend-eventmanager 2.4.8 -> satisfiable by zendframework/zend-eventmanager[2.4.8].
    - zendframework/zend-code 2.4.7 requires zendframework/zend-eventmanager 2.4.7 -> satisfiable by zendframework/zend-eventmanager[2.4.7].
    - zendframework/zend-code 2.4.6 requires zendframework/zend-eventmanager 2.4.6 -> satisfiable by zendframework/zend-eventmanager[2.4.6].
    - zendframework/zend-code 2.4.5 requires zendframework/zend-eventmanager 2.4.5 -> satisfiable by zendframework/zend-eventmanager[2.4.5].
    - zendframework/zend-code 2.4.4 requires zendframework/zend-eventmanager 2.4.4 -> satisfiable by zendframework/zend-eventmanager[2.4.4].
    - zendframework/zend-code 2.4.3 requires zendframework/zend-eventmanager 2.4.3 -> satisfiable by zendframework/zend-eventmanager[2.4.3].
    - zendframework/zend-code 2.4.2 requires zendframework/zend-eventmanager 2.4.2 -> satisfiable by zendframework/zend-eventmanager[2.4.2].
    - zendframework/zend-code 2.4.1 requires zendframework/zend-eventmanager 2.4.1 -> satisfiable by zendframework/zend-eventmanager[2.4.1].
    - zendframework/zend-code 2.4.0 requires zendframework/zend-eventmanager 2.4.0 -> satisfiable by zendframework/zend-eventmanager[2.4.0].
    - zendframework/zend-code 2.3.9 requires zendframework/zend-eventmanager 2.3.9 -> satisfiable by zendframework/zend-eventmanager[2.3.9].
    - zendframework/zend-code 2.3.8 requires zendframework/zend-eventmanager 2.3.8 -> satisfiable by zendframework/zend-eventmanager[2.3.8].
    - zendframework/zend-code 2.3.7 requires zendframework/zend-eventmanager 2.3.7 -> satisfiable by zendframework/zend-eventmanager[2.3.7].
    - zendframework/zend-code 2.3.6 requires zendframework/zend-eventmanager 2.3.6 -> satisfiable by zendframework/zend-eventmanager[2.3.6].
    - zendframework/zend-code 2.3.5 requires zendframework/zend-eventmanager 2.3.5 -> satisfiable by zendframework/zend-eventmanager[2.3.5].
    - zendframework/zend-code 2.3.4 requires zendframework/zend-eventmanager 2.3.4 -> satisfiable by zendframework/zend-eventmanager[2.3.4].
    - zendframework/zend-code 2.3.3 requires zendframework/zend-eventmanager 2.3.3 -> satisfiable by zendframework/zend-eventmanager[2.3.3].
    - zendframework/zend-code 2.3.2 requires zendframework/zend-eventmanager 2.3.2 -> satisfiable by zendframework/zend-eventmanager[2.3.2].
    - zendframework/zend-code 2.3.1 requires zendframework/zend-eventmanager 2.3.1 -> satisfiable by zendframework/zend-eventmanager[2.3.1].
    - zendframework/zend-code 2.3.0 requires zendframework/zend-eventmanager 2.3.0 -> satisfiable by zendframework/zend-eventmanager[2.3.0].
    - zendframework/zend-code 2.2.9 requires zendframework/zend-eventmanager 2.2.9 -> satisfiable by zendframework/zend-eventmanager[2.2.9].
    - zendframework/zend-code 2.2.8 requires zendframework/zend-eventmanager 2.2.8 -> satisfiable by zendframework/zend-eventmanager[2.2.8].
    - zendframework/zend-code 2.2.7 requires zendframework/zend-eventmanager 2.2.7 -> satisfiable by zendframework/zend-eventmanager[2.2.7].
    - zendframework/zend-code 2.2.6 requires zendframework/zend-eventmanager 2.2.6 -> satisfiable by zendframework/zend-eventmanager[2.2.6].
    - zendframework/zend-code 2.2.10 requires zendframework/zend-eventmanager 2.2.10 -> satisfiable by zendframework/zend-eventmanager[2.2.10].
    - zendframework/zend-eventmanager 2.4.9 requires zendframework/zend-stdlib 2.4.9 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.8 requires zendframework/zend-stdlib 2.4.8 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.7 requires zendframework/zend-stdlib 2.4.7 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.6 requires zendframework/zend-stdlib 2.4.6 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.5 requires zendframework/zend-stdlib 2.4.5 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.4 requires zendframework/zend-stdlib 2.4.4 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.3 requires zendframework/zend-stdlib 2.4.3 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.2 requires zendframework/zend-stdlib 2.4.2 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.1 requires zendframework/zend-stdlib 2.4.1 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.0 requires zendframework/zend-stdlib 2.4.0 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.9 requires zendframework/zend-stdlib 2.3.9 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.8 requires zendframework/zend-stdlib 2.3.8 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.7 requires zendframework/zend-stdlib 2.3.7 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.6 requires zendframework/zend-stdlib 2.3.6 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.5 requires zendframework/zend-stdlib 2.3.5 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.4 requires zendframework/zend-stdlib 2.3.4 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.3 requires zendframework/zend-stdlib 2.3.3 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.2 requires zendframework/zend-stdlib 2.3.2 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.1 requires zendframework/zend-stdlib 2.3.1 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.0 requires zendframework/zend-stdlib 2.3.0 -> no matching package found.
    - zendframework/zend-eventmanager 2.2.9 requires zendframework/zend-stdlib 2.2.9 -> no matching package found.
    - zendframework/zend-eventmanager 2.2.8 requires zendframework/zend-stdlib 2.2.8 -> no matching package found.
    - zendframework/zend-eventmanager 2.2.7 requires zendframework/zend-stdlib 2.2.7 -> no matching package found.
    - zendframework/zend-eventmanager 2.2.6 requires zendframework/zend-stdlib 2.2.6 -> no matching package found.
    - zendframework/zend-eventmanager 2.2.10 requires zendframework/zend-stdlib 2.2.10 -> no matching package found.
    - Conclusion: don't install ocramius/proxy-manager 1.0.2
    - Conclusion: don't install ocramius/proxy-manager 1.0.1
    - Conclusion: don't install zendframework/zend-code 2.5.0
    - Conclusion: don't install zendframework/zend-code 3.0.1|install zendframework/zend-code 2.5.0
    - Installation request for ocramius/proxy-manager ^1.0 -> satisfiable by ocramius/proxy-manager[1.0.0, 1.0.1, 1.0.2].
    - Conclusion: remove zendframework/zend-code 3.0.1|install zendframework/zend-code 2.5.0
    - ocramius/proxy-manager 1.0.0 requires zendframework/zend-code >2.2.5,<3.0 -> satisfiable by zendframework/zend-code[2.2.10, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2].
    - Can only install one of: zendframework/zend-code[2.5.1, 3.0.1].
    - Can only install one of: zendframework/zend-code[2.5.2, 3.0.1].
    - Can only install one of: zendframework/zend-code[2.5.3, 3.0.1].
    - Can only install one of: zendframework/zend-code[2.6.0, 3.0.1].
    - Can only install one of: zendframework/zend-code[2.6.1, 3.0.1].
    - Can only install one of: zendframework/zend-code[2.6.2, 3.0.1].
    - Installation request for zendframework/zend-code == 3.0.1.0 -> satisfiable by zendframework/zend-code[3.0.1].

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by Repkit** [comment]
try adding directly in your composer.json file and then run composer update comand

**Comment by webdesign7** [comment]
@Repkit thanks for suggestion .. I think it worked this way!  .. the only thing now I got this error after composer finishes pulling packages: 

 [ErrorException]  
  file_put_contents(/Users/sergiu/Sites/zend-expressive-tutorial/vendor/ocramius/package-versions/src/PackageVersions/Versions.php  
  ): failed to open stream: No such file or directory

**Comment by geerteltink** [comment]
Something might have messed up the composer plugin. Can you remove ocramius/package-versions manually, do a `composer update` and then require package-versions again.

**Comment by webdesign7** [comment]
Worked as per your suggestion ! Thanks ...  however not sure if that would be the right approach as if you do a fresh installation then immediately requiring packages through composer it give some sort of errors .. which then you do need to do manual tweak in order to have it working properly. Apart from that all good .. Cheers

**Comment by webdesign7** [comment]
FYI :   just noticed that when I have manually required ocramius again it updated composer.json with :  **"ocramius/proxy-manager": "^2.0"**  instead of  "ocramius/proxy-manager": "^1.0" ( which originally comes with installation )
