### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by webdesign7** [RalfEggert/zend-expressive-tutorial#22]
good tutorial .. done it all ! 
just a typo in this bit:

https://github.com/RalfEggert/zend-expressive-tutorial/blob/part4/doc/book/part5.md#add-delete-action-for-form-handling

/**
- Class AlbumDeleteHandleAction
  *
- @package Album\Action
  */
  class AlbumDeleteFormAction
  {

Regards

**Comment by RalfEggert** [comment]
Fixed
