### ISSUE TITLE
Incorrect file name global.autoload.php

### ISSUE THREAD

**Issue by SBC-Dana** [RalfEggert/zend-expressive-tutorial#23]
Hi Ralph, 

I'm following through the tutorial and noticed that in documentation for "Part 4: Forms and input filter" under "Add form view helpers to helper plugin manager" it states "Enable custom factory in  config/autoload/templates/global.autoload.php file. Replace following definition:". I believe it should read "Enable custom factory in  config/autoload/templates.global.php" as folder "templates" and file "global.autoload.php" do not exist.  

Thanks for the great tutorial !!

**Comment by RalfEggert** [comment]
Since there is no need of adding the form view helpers manually any more the text block was removed.
