### ISSUE TITLE
AbstractPluginManager::__construct and ZF v3

### ISSUE THREAD

**Issue by hl4892** [RalfEggert/zend-expressive-tutorial#26]
Hello,
Due to a changes in ServiceManager v3 in part 4 and higher in the src/App/View/HelperPluginManagerFactory.php:

`// REPLACE:        $manager = new HelperPluginManager(new Config($config)); WITH:

$manager = new HelperPluginManager($container);

 //DELETE: $manager->setServiceLocator($container);`

Best regards,
Marcin

**Comment by RalfEggert** [comment]
This issue was already fixed some days ago. There is no need of the custom factory any more.
