### ISSUE TITLE
Plugin by the name "form" was not found.

### ISSUE THREAD

**Issue by tasmaniski** [RalfEggert/zend-expressive-tutorial#28]
Following the tutorials at the end of part 4 I got an error:

> A plugin by the name "form" was not found in the plugin manager Zend\View\HelperPluginManager

After research I see that there is a difference in ./config/config.php 
This is the [config.php](https://github.com/RalfEggert/zend-expressive-tutorial/blob/part4/config/config.php) from tutorial's part4 and from current [zend-expressive-skeleton](https://github.com/zendframework/zend-expressive-skeleton/blob/master/config/config.php)

In tutorial's part1 after installation of expressive I got new version of config.php file,
which occur an error in part4.

**Comment by RalfEggert** [comment]
The tuturial is using the https://packagist.org/packages/mtymek/expressive-config-manager which works nicely with the https://github.com/zendframework/zend-component-installer. This results in the different `config.php` files. Since the `\Zend\Form\ConfigProvider::class,` is added there it should work.

I am not sure about your last sentence. When does your error occur?

**Comment by tasmaniski** [comment]
The error occur in tutorial's part4.  

After I installed **mtymek/expressive-config-manager** package and change the config.php file everything works fine. But there is nothing about that in tutorial :) 

In any case the tutorial is very good and helped me a lot to understand and practice basics of zend-expressive. Thanks!

**Comment by RalfEggert** [comment]
I will check this in the next couple of days.

**Comment by RalfEggert** [comment]
I added the installation of the `Zend\ComponentInstaller` and the `Zend\Expressive\ConfigManager` now in the tutorial for part1. I also documented what happens when a new ZF component is installed in parts 2, 3 and 4. 

So your problems shouldn't occur any more.

**Comment by tasmaniski** [comment]
that's all we need :) 
tnx
