### ISSUE TITLE
Unnecesary dependencies key in database.global.php

### ISSUE THREAD

**Issue by xorock** [RalfEggert/zend-expressive-tutorial#29]
In config.php You are using \Zend\Db\ConfigProvider::class which already registers factories and abstract_factories for Zend\Db. Keys are duplicated in database.global.php

**Comment by RalfEggert** [comment]
Yep. This is due to the fact, that the `Zend\ComponentInstaller` wasn't around when I wrote the tutorial. I will update this part in the next couple of days.

**Comment by RalfEggert** [comment]
Fixed now with the latest update:

https://github.com/RalfEggert/zend-expressive-tutorial/blob/part3/config/autoload/database.global.php
