### ISSUE TITLE
Template directory ambiguity

### ISSUE THREAD

**Issue by robob4him** [RalfEggert/zend-expressive-tutorial#30]
Being unfamiliar with the expressive directory structure, I thought the template directory was relative to src/Album/Action. Did I miss a reference that all directory statements were absolute from the project root?

**Comment by RalfEggert** [comment]
Could define more precisely which part of the tutorial you found this issue?

**Comment by robob4him** [comment]
@RalfEggert https://github.com/RalfEggert/zend-expressive-tutorial/blob/part1/doc/book/part2.md#create-a-template-for-listing-albums

I initially created the templates folder under the module until the [Provide navigation](https://github.com/RalfEggert/zend-expressive-tutorial/blob/part1/doc/book/part2.md#provide-navigation) section referenced the default layout. Then I realized it was relative to the project root.

**Comment by RalfEggert** [comment]
Ok, thanks. I added a comment to create the directory in the root of the project.

https://github.com/RalfEggert/zend-expressive-tutorial/blob/part1/doc/book/part2.md#create-a-template-for-listing-albums
