### ISSUE TITLE
Update phpunit.xml document

### ISSUE THREAD

**Issue by robob4him** [RalfEggert/zend-expressive-tutorial#31]
Setup PHPUnit should be updated - the phpunit.xml.dist file has been updated since with more filters.

**Comment by RalfEggert** [comment]
Will be done in the next couple of days

**Comment by RalfEggert** [comment]
Was updated with the latests commits:

https://github.com/RalfEggert/zend-expressive-tutorial/blob/part1/phpunit.xml.dist
