### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by robob4him** [RalfEggert/zend-expressive-tutorial#32]
https://github.com/RalfEggert/zend-expressive-tutorial/blob/4b37066506921aa1fbcac508dcc7c413c657e747/doc/book/part3.md#update-the-album-configuration has a typo. "applicaition" should be "application"

https://github.com/RalfEggert/zend-expressive-tutorial/blob/part6/doc/book/part4.md#create-album-form-create-action has a confusing sentence "It does not handle the form when send."

https://github.com/RalfEggert/zend-expressive-tutorial/blob/part6/doc/book/part5.md#add-delete-action-to-show-form has a typo in the second paragraph. "from" should be "form".

https://github.com/RalfEggert/zend-expressive-tutorial/blob/part6/doc/book/part5.md#add-delete-action-for-form-handling has a typo. "delete_album_yes was send" should be "delete_album_yes was sent".

**Comment by RalfEggert** [comment]
Thanks. I will fix that soon.

**Comment by RalfEggert** [comment]
Thanks again. I just fixed all typos.
