### ISSUE TITLE
Error in step for part 6

### ISSUE THREAD

**Issue by robob4him** [RalfEggert/zend-expressive-tutorial#33]
https://github.com/RalfEggert/zend-expressive-tutorial/blob/part6/doc/book/part6.md#remove-unused-configuration should not remove autoload-dev from the composer.json file, should it? It contains the AlbumTest pathing.

**Comment by RalfEggert** [comment]
Thanks for reporting, I will check that as well!

**Comment by RalfEggert** [comment]
Fixed:

https://github.com/RalfEggert/zend-expressive-tutorial/commit/7b67f9696ac364017535b8acd68a26ae8e2822ed
