### ISSUE TITLE
Form handling middleware

### ISSUE THREAD

**Issue by RalfEggert** [RalfEggert/zend-expressive-tutorial#8]
I am playing around with a special middleware to handle the form data. So I plan to split up the `AlbumCreateAction` in form display and form handling. That would mean that complete `if` block will be removed from `AlbumCreateAction`. 

I would add another `FormCreateAction` which is only routed for POST methods. This new `FormCreateAction` has dependencies to the router, the service and the form and basically has the contents from the current `if` block. When the saving or the form validation fails I would pass on to the `AlbumCreateAction` again. This would mean that I am also injecting the `AlbumCreateAction` instance to my `FormCreateAction` instance and pass on like this:

```
$failureAction = $this->formCreateAction;

return $failureAction($request, $response, $next);
```

Is this a good practice? Or is there another way to call the `FormCreateAction` if the saving and form validation stops? Can I route to another action middleware for the same route?

What do you think about this?

**Comment by RalfEggert** [comment]
Ok, I just found out, that in the routing I can add an array of middleware. Then I don't need to inject `AlbumCreateAction`. And I just can pass on by

```
return $next($request, $response);
```

**Comment by mtymek** [comment]
:+1: for separation of concerns - SRP FTW! :smile:

**Comment by weierophinney** [comment]
> Ok, I just found out, that in the routing I can add an array of middleware. Then I don't need to inject AlbumCreateAction. And I just can pass on

I think @michaelmoussa will be very pleased with this application of that feature! (It's exactly what it was intended for!)

**Comment by michaelmoussa** [comment]
I love when stuff ends up being useful for others too! :) :beers:

**Comment by RalfEggert** [comment]
Ok, great than. I will give it a try when the #6 decisions are implemented.

**Comment by RalfEggert** [comment]
Have implemented the separated actions for the form handling now

https://github.com/RalfEggert/zend-expressive-tutorial/tree/part6/src/Album/Action
